version: "3.2"
services: 
    db:
        image: postgres
        container_name: db
        restart: always
        ports: 
            - 8080:8080
        environment: 
            POSTGRES_PASSWORD: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            
